AllCops:
  Exclude:
    - db/schema.rb
    - db/**/*.rb
    - config/**/*.rb
    - script/**
    - bin/**
    - spec/rails_helper.rb
    - spec/spec_helper.rb
Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb

